language: node_js
node_js:
- '10'
- '11'
- '12'
- '13'
- lts/*
- node
deploy:
  provider: npm
  email: nessthehero@gmail.com
  api_key:
    secure: KrRUHNp8vGZSFK2Fh+BQsWM6MswJiWR3ROqFAgjndNAAoJiN6GDZ7n3GAJlFyxoC2+z07fhRvyBmFr8g6JdTBtvNWcmc05J1acxLqCP6nS4qMYvsFE6BI0dXhGcqMsAilDgsGRFiuDI1ehU/VApEeu8J8OfavhHbVIBSTuOI7hD5UX7OH4i4FDPEFPJM8ycFwJLD9yNRGM6MBiJgMzypW8tedcBoMBX9GnONLcrhbi+V+aruL3hvjWu42EkgLStoTMYGwSnWauyaIIO7ncYDFz3dhbkE85Zj8caNfdD1zv0cBaEDzUUrll0X38kG5keOahDQwUra8x0BIlVhLMQP9J1I5hgin4jzoAB5E4EyKG2cRXzOIP130tZcXURIWBN04eXSCcmPklHUla52CseMnqrrFGvHydBmJnopxsznoP0Q9Ww1xRiYg+7Jh3zUdC1UvMqftg5GYwmapbiCVZvKIrAzK1hMN8utA3scvjQ3NBA8UCwTryx5o5/+01ITq+lorTtjv+XAuWISxhPtoL3jjE0GuKweHULJW3r5r4Hdj5yKYwWKm0RbDaUXJ4HN1vof81ideYT5nop8YVWMBiGy4hsSSqarGVv+53mNiTbKT70Rfzb3YJm9m8pzPpv0xT7pvmGfvS0KJAwdw0/NdcjXvB0cSQq3HJ9/AzwBrVLzU3Y=
  on:
    tags: true
    repo: BarkleyREI/brei-sass-mixins
  skip_cleanup: 'true'
